# Use an official Python runtime as a parent image
FROM mmdnn/mmdnn:cpu.small

USER root

# Set the working directory to /app
WORKDIR /

# Define environment variable
# ENV NAME World

# Run app.py when the container launches
# CMD ["python", "app.py"]
