# Use an official Python runtime as a parent image
FROM bvlc/caffe:cpu

USER root

# Set the working directory to /app
WORKDIR /

# Define environment variable
# ENV NAME World

# Run app.py when the container launches
# CMD ["python", "app.py"]
